- index.html
- script.js
- style.css
- Replace JQuery with plain JS
- Remove extra references for smoothie.js
- Fix issue of canvas size
> Minor Bug Fixes

- index.html
- script.js
- Add padding to charts
- Use stop() method to destroy smoothie charts before redraw
> - Fix Corrupted data due to errror while refreshing buffer

- index.html
- script.js
Done some changes in index.html.
> Revamp code

- script.js
- Replace TextDecoderStream() with mannual stream to allow use of releaseLock() method.
- Show alert when no port is selected
> Fix issue #9

- script.js
WebSerial only works on chrome, added alert if user is on a different browser. Enter the commit message for your changes.
> Detect browser

- README.md
- script.js
Removed jQuery references as it is no longer in use.
> Updated Readme.md

- index.html
- script.js
- style.css
-Implement browser compatibility check on web page load
-Display incompatibility message for non-Chrome browsers
[live](https://ritika8081.github.io/BioSignal-Recorder-Web/)
> fixed  issue  #17

- script.js
- Provides clear information to users, enhancing the overall user experience.
- If connected to an external device, display the channel number.
- If not connected to an external device, display the message "No device connected."
> add connection status to chart

- index.html
- script.js
- style.css
- Add link to list of compatible broswers in Compatiblity Message
- Removed chrome specific conditions
- Works on all compatible broswers (Chrome, Edge and Opera)
> Fix issue #20

- script.js
- Start/Stop Button is disabled when recording and saving data
- Visualiser is stoped when saving data to file
> Fix issue #15

- script.js
- add '-1' in all columns to show pause event
- add header columns in csv
- improve saving to file speed by changing MIN_BATCH_SIZE and highWaterMark
> Fix issue #23

- index.html
- script.js
replaced text button with icons and stop data signals on screen .
[link](https://ritika8081.github.io/BioSignal-Recorder-Web/)
Next task :
> fixed #26  Icons as buttons, click stop to pause data graph.

- package-lock.json
- package.json
- src/components/Canvas.tsx
@lorforlinux I was trying to fix theme change while chart is paused, I didn't tried with random data, due to no device the commit was experimental, reverting the changes in this.
> Reverting canvas theme change trial

- package-lock.json
- src/components/Connection.tsx
Format code to get data from arduino R3
> Data handling for Arduino R3

- README.md
- src/components/Canvas.tsx
- src/components/Connection.tsx
@lorforlinux please review, I have optimized the IndexedDB logic by implementing batch writes.
> updated indexed db logic

- src/app/globals.css
- src/components/Canvas.tsx
- src/components/Connection.tsx
- src/components/DataPass.tsx
- src/components/LandingComp/FAQSection.tsx
- src/components/LandingComp/Footer.tsx
- src/components/LandingComp/Steps.tsx
- src/components/Navbar.tsx
- src/components/Steps.tsx
@lorforlinux,
I have made significant updates to the repository, including improvements to both the plotting logic and the user interface. Here is a summary of the changes:
Plotting Logic:
- Previously, the plot would shift as new data streamed in, showing a continuous data flow.
- Now, the plot refreshes by overwriting old data instead of shifting. This change ensures smoother performance and keeps the latest data always clearly visible.
User Interface Changes:
- Removed the border around the canvas for a cleaner and more streamlined appearance.
- Updated background colors and introduced curved buttons for the canvas, enhancing the visual appeal and organization of the app.
- Improved the UI for the steps feature, making it more user-friendly.
- These enhancements are intended to improve …
> Updated UI elements and improved data pLotting

- Version.tsx
- package.json
- src/components/Canvas.tsx
- src/components/Connection.tsx
- src/components/Contributors.tsx
- src/components/DataPass.tsx
- src/components/boards.ts
- src/components/filters.tsx
Hi @lorforlinux,
I have implemented the following updates to the repository:
1. Added support of maker uno which should work on any UNO R3 clone with CH340 chip.
2. Added  board entry for Arduino UNO R4 WiFi.
3. Added frame buffer feature in which we can  view up to last five snapshots of your data and save them as images.
4. Updated readme for roadmap about upcoming updates.
You can view and test the live project here: https://amanmahe.github.io/Chords-Web
Please review the changes and let me know if you have any feedback or if further modifications are required.
Thank you for your time and consideration!
Best regards,
Amanmahe
> Added frame buffer and new device support

- README.md
- package-lock.json
- package.json
- src/components/Canvas.tsx
- src/components/Connection.tsx
- src/components/DataPass.tsx
- src/components/boards.ts
- src/components/filters.tsx
Hi @lorforlinux,
I have implemented the following updates to the repository:
1. Added board entry for Raspberry Pi Pico,providing upto 3 channels of analog input.
2. Added a feature to download multiple files, allowing users to record multiple files, download/delete them individually. Additionally, master buttons have been added to download all files as a ZIP and delete all files at once.
3. Updated the CSV data format and file names. now you can use [csvplotter.py ](https://github.com/upsidedownlabs/Chords-Python/blob/main/csvplotter.py) to visualise the recorded csv data.
You can view and test the live project here: https://amanmahe.github.io/Chords-Web
Please review the changes and let me know if you have any feedback or if further modifications are required.
Thank you for your time …
> Added Multiple recording file feature,Raspberry Pi Pico device support and updated csv format.

- package-lock.json
- package.json
Reverts upsidedownlabs/Chords-Web#60
> Revert "Bump next from 14.2.10 to 14.2.15"

- README.md
@lorforlinux please review, I have updated roadmap in readme file according to updates.
> Updated roadmap in readme.md file.

- src/components/boards.ts
@lorforlinux please review, To support Arduino Uno R3 we included field_pid 579.
> Included field_pid for Arduino Uno R3

- README.md
- package-lock.json
- package.json
- src/components/Canvas.tsx
@lorforlinux please review, I have done following changes in application :
> Code Updates to Resolve Issues
